# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded !"
set -g mouse on
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

bind-key - split-window -v  
bind-key | split-window -h 

bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

unbind '"'
unbind %
unbind ^H

# osx clipboard
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Open current directory
bind o run-shell "open '#{pane_current_path}'"


bind-key Space run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 90%,80% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' 
)\""

bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4

bind Escape kill-pane
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

set -g base-index 1 # start index at 1
set -g pane-base-index 1
set -sg escape-time 10

source ~/.config/tmux/theme.conf
source ~/.config/tmux/macos.conf
source ~/.config/tmux/popup.conf

## tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jerek/catppuccin-tmux-fixed-transparency#transparent-status-background-support'

run '~/.tmux/plugins/tpm/tpm'

set -g allow-rename on
set -g automatic-rename on
