set -g status-position top 

set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right-length 100
set -g status-left-length 100
set -g status-right ""
