blacklist = ["scratch", "claude-*", "opencode-*"]

[[session]]
name = "bo-admin"
path = "~/Projects/front/bo-admin"
startup_command = "n"
windows = ["api"]

[[session]]
name = "bo-hub"
path = "~/Projects/front/bo-hub"
startup_command = "n"
windows = ["api"]

[[session]]
name = "bo-transporter"
path = "~/Projects/front/bo-transporter"
startup_command = "n"
windows = ["api"]

[[session]]
name = "bo-store"
path = "~/Projects/front/bo-store"
startup_command = "n"
windows = ["api"]

[[session]]
name = "bo-client"
path = "~/Projects/front/bo-client"
startup_command = "n"
windows = ["api"]

[[session]]
name = "bo-visibility"
path = "~/Projects/idl/bo-visibility"
startup_command = "n"

[[session]]
name = "midgard"
path = "~/Projects/front/midgard/"
startup_command = "n"
windows = ["api"]

[[session]]
name = "courier app"
path = "~/Projects/front/courier-mobile-app/"
startup_command = "n"

[[session]]
name = "hub app"
path = "~/Projects/front/hub-app-mobile/"
startup_command = "n"

[[session]]
name = "login"
path = "~/Projects/front/login/"
startup_command = "n"

[[session]]
name = "perso"
path = "~/Projects/perso/"

[[session]]
name = "e2e"
path = "~/Projects/e2e-tests/"

[[window]]
name = "api"
path = "~/Projects/front/api"
startup_script = "n"
