return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    ensure_installed = {
      "rescript",
      "gitignore",
      "json",
      "gitignore",
      "css",
      "go",
      "http",
      "vim",
      "typescript",
      "javascript",
      "lua",
      "html",
      "markdown",
      "markdown_inline",
      "yaml",
      "tsx",
    },
  },
}
