#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="JetBrainsMonoNL Nerd Font"
ICON_FONT="SF Pro"

##### Bar Appearance #####
BAR_PROPS=(
  position=top
  height=36
  # blur_radius=30
  color=0x00000000
  corner_radius=14
  margin=0
  y_offset=6
)

sketchybar --bar "${BAR_PROPS[@]}"

##### Changing Defaults #####
DEFAULT_PROPS=(
  padding_left=6
  padding_right=6
  icon.font="$FONT:Bold:16.0"
  label.font="$FONT:Bold:16.0"
  icon.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=6
  background.height=20
  label.color=$WHITE
  icon.padding_left=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${DEFAULT_PROPS[@]}"

source "$CONFIG_DIR/items/aerospace.sh"

sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item clock q \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh"

source "$CONFIG_DIR/items/meeting.sh"
source "$CONFIG_DIR/items/battery.sh"
source "$CONFIG_DIR/items/volume.sh"
source "$CONFIG_DIR/items/cpu.sh"
source "$CONFIG_DIR/items/mail.sh"

##### Section brackets #####
sketchybar --add bracket left_section '/space\..*/' chevron front_app \
  --set left_section background.color=$BASE background.corner_radius=8 background.height=28 padding_left=0 padding_right=0

sketchybar --add bracket center_section clock \
  --set center_section background.color=$BASE background.corner_radius=8 background.height=28

sketchybar --add bracket right_section meeting battery volume cpu mail \
  --set right_section padding_left=0 padding_right=0

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
